$(document).ready(function(){
    $("#gform").validate({
        rules:{
            uname:{
                required:true
            },
            uemail:{
                required:true,
                email:true
            }
        }
    })
})